name: Embedded Driver CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up GCC and Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Compile Shared Library
      run: |
        make all

    - name: Run Embedded Test Suite
      run: |
        make test
